"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
type Prospect={id:string;name:string;company:string;phone:string;email:string;profile:string;source:string;type:string;interest:string;budget:number;zone:string;property:string[];status:string;score:number;notes:string;date:string};
const SOURCES=["Facebook","Instagram","Google","TikTok","LinkedIn","Web","Referido","Otro"];
const TYPES=["Comprador","Inversionista","Arrendatario","Propietario","Otro"];
const STATUSES=["Nuevo","Por calificar","Calificado","Contactado","Conversación","Oportunidad","Descartado"];
const EMPTY={name:"",company:"",phone:"",email:"",profile:"",source:"Facebook",type:"Comprador",interest:"",budget:"",zone:"Santa Ana",status:"Nuevo",score:"50",notes:""};
export default function ProspectingCenter(){
 const [query,setQuery]=useState("compradores de propiedades en Santa Ana"),[items,setItems]=useState<Prospect[]>([]),[draft,setDraft]=useState(EMPTY),[source,setSource]=useState("Todas"),[status,setStatus]=useState("Todos"),[min,setMin]=useState("0"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[selected,setSelected]=useState<Prospect|null>(null),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/prospecting",{cache:"no-store"});const p=await r.json();if(!r.ok)throw Error(p.error);setItems(p.prospects||[])}catch(e){setMessage(e instanceof Error?e.message:"No se pudo cargar prospecting.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const results=useMemo(()=>items.filter(p=>(source==="Todas"||p.source===source)&&(status==="Todos"||p.status===status)&&p.score>=Number(min)),[items,source,status,min]);
 const searchLinks={google:`https://www.google.com/search?q=${encodeURIComponent(query)}`,maps:`https://www.google.com/maps/search/${encodeURIComponent(query)}`,facebook:`https://www.facebook.com/search/pages/?q=${encodeURIComponent(query)}`,trends:`https://trends.google.com/trends/explore?geo=SV&q=${encodeURIComponent(query)}`};
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const r=await fetch("/api/prospecting",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,budget:Number(draft.budget)||0,score:Number(draft.score)||0})});const p=await r.json();if(!r.ok)throw Error(p.error);setItems(x=>[p.prospect,...x]);setDraft(EMPTY);setMessage("Prospecto guardado en Prospectos_FBR.")}catch(e){setMessage(e instanceof Error?e.message:"No se pudo guardar.")}finally{setSaving(false)}}
 return <section className="prospecting"><header><small>PROSPECTING AI</small><h1>Encuentra clientes para las propiedades.</h1><p>Busca una audiencia, revisa las fuentes y registra prospectos en el mismo centro.</p></header>
 <div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ej. inversionistas interesados en Santa Ana"/><div><a href={searchLinks.google} target="_blank" rel="noreferrer">Google ↗</a><a href={searchLinks.maps} target="_blank" rel="noreferrer">Maps ↗</a><a href={searchLinks.facebook} target="_blank" rel="noreferrer">Facebook ↗</a><a href={searchLinks.trends} target="_blank" rel="noreferrer">Trends ↗</a></div></div>
 <div className="stats"><b>{items.length}<span>prospectos</span></b><b>{items.filter(p=>p.status!=="Descartado").length}<span>activos</span></b><b>{items.filter(p=>p.score>=70&&p.status!=="Descartado").length}<span>alto potencial</span></b></div>
 <div className="grid"><form onSubmit={save} className="card"><small>NUEVO PROSPECTO</small><h2>Registrar resultado</h2><div className="fields">
 {[['name','Nombre'],['company','Empresa'],['phone','Teléfono'],['email','Email'],['profile','Perfil / URL'],['zone','Zona']].map(([k,l])=><label key={k}>{l}<input required={k==='name'} value={(draft as any)[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 <label>Fuente<select value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}>{SOURCES.map(x=><option key={x}>{x}</option>)}</select></label><label>Tipo<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Presupuesto<input type="number" value={draft.budget} onChange={e=>setDraft({...draft,budget:e.target.value})}/></label><label>Score<input type="number" min="0" max="100" value={draft.score} onChange={e=>setDraft({...draft,score:e.target.value})}/></label><label>Estado<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Interés / necesidad<textarea value={draft.interest} onChange={e=>setDraft({...draft,interest:e.target.value})}/></label><label className="wide">Notas<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div><button disabled={saving}>{saving?"Guardando…":"Guardar prospecto"}</button></form>
 <section className="card"><div className="resultHead"><div><small>RESULTADOS</small><h2>Prospectos encontrados</h2></div><button onClick={()=>void load()} disabled={loading}>{loading?"…":"Actualizar"}</button></div><div className="filters"><select value={source} onChange={e=>setSource(e.target.value)}><option>Todas</option>{SOURCES.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</select><select value={min} onChange={e=>setMin(e.target.value)}><option value="0">Todos</option><option value="50">50+</option><option value="70">70+</option><option value="85">85+</option></select></div>{results.length?<div className="list">{results.map(p=><button className="row" key={p.id} onClick={()=>setSelected(p)}><strong>{p.score}</strong><div><b>{p.name}</b><span>{p.type} · {p.source} · {p.status}</span><p>{p.interest||p.company||"Sin información adicional"}</p></div></button>)}</div>:<div className="empty">No hay prospectos con estos filtros.</div>}</section></div>
 {selected?<aside className="detail"><button onClick={()=>setSelected(null)}>×</button><small>{selected.source} · {selected.status}</small><h2>{selected.name}</h2><strong>Score {selected.score}/100</strong><p>{selected.company}</p><p>{selected.interest||"Sin interés registrado."}</p><p>{selected.zone} {selected.budget?`· Presupuesto $${selected.budget.toLocaleString()}`:""}</p>{selected.phone&&<p>📞 {selected.phone}</p>}{selected.email&&<p>✉ {selected.email}</p>}{selected.profile&&<a href={selected.profile} target="_blank" rel="noreferrer">Abrir perfil ↗</a>}</aside>:null}
 {message&&<div className="message">{message}</div>}
 <style jsx>{`.prospecting{padding:8px 0 30px;color:#111827}.prospecting header small,.card>small,.resultHead small{font-size:10px;font-weight:900;letter-spacing:.15em;color:#64748b}.prospecting h1{font-size:clamp(28px,4vw,48px);letter-spacing:-.05em;margin:5px 0}.prospecting header p{color:#64748b;font-size:14px}.search{margin:22px 0;padding:8px;border:1px solid #e2e8f0;border-radius:18px;background:#fff;display:flex;gap:10px}.search input{flex:1;border:0;outline:0;padding:10px;font-size:14px}.search div{display:flex;gap:6px}.search a{padding:9px 11px;background:#f1f5f9;border-radius:10px;font-size:12px;text-decoration:none;color:#2563eb}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:16px}.stats b{font-size:24px;padding:14px;border-block:1px solid #e2e8f0}.stats span{display:block;font-size:11px;font-weight:500;color:#64748b}.grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:14px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:18px}.card h2{font-size:20px;margin:5px 0 16px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.fields label{font-size:11px;color:#64748b}.fields .wide{grid-column:1/-1}.fields input,.fields select,.fields textarea{display:block;width:100%;box-sizing:border-box;margin-top:5px;border:1px solid #dbe3ee;border-radius:10px;padding:9px;font:inherit;font-size:12px}.fields textarea{min-height:58px}.card>button,.resultHead>button{margin-top:14px;border:0;border-radius:10px;padding:10px 14px;background:#2563eb;color:#fff;font-weight:800}.resultHead{display:flex;justify-content:space-between;align-items:center}.resultHead>button{margin:0;background:#eef2ff;color:#2563eb}.filters{display:flex;gap:7px;margin:14px 0}.filters select{border:1px solid #dbe3ee;border-radius:9px;padding:8px;font-size:11px}.list{display:grid;gap:7px}.row{display:grid;grid-template-columns:44px 1fr;text-align:left;gap:10px;border:1px solid #e2e8f0;border-radius:12px;background:#fff;padding:11px;cursor:pointer}.row>strong{font-size:17px;color:#2563eb}.row b,.row span,.row p{display:block}.row span,.row p{font-size:11px;color:#64748b;margin-top:3px}.row p{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.empty{padding:30px;text-align:center;color:#64748b;font-size:12px}.detail{position:fixed;right:20px;top:20px;width:320px;max-width:calc(100vw - 40px);padding:22px;background:#fff;border:1px solid #e2e8f0;border-radius:18px;box-shadow:0 20px 50px #0002;z-index:20}.detail>button{float:right;border:0;background:none;font-size:24px}.detail h2{margin:20px 0 8px}.detail small{color:#64748b}.detail a{color:#2563eb;font-size:12px}.message{position:fixed;bottom:20px;right:20px;padding:12px 16px;background:#111827;color:#fff;border-radius:10px;font-size:12px}@media(max-width:900px){.grid{grid-template-columns:1fr}.search{display:block}.search div{margin-top:8px;overflow:auto}.fields{grid-template-columns:1fr}.fields .wide{grid-column:auto}}`}</style></section>
}